# Generated by Django 3.2.15 on 2022-09-02 11:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the instance this object belongs to. \n            Mandatory, unless a new instance to create is given.', primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, help_text='The IP Address of the user at the time of creating record.', null=True, verbose_name='IP Address')),
                ('location', models.JSONField(default=None, null=True)),
                ('time_zone', models.JSONField(default=None, null=True)),
                ('currency', models.JSONField(default=None, null=True)),
                ('connection', models.JSONField(default=None, null=True)),
                ('security', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and \n            time are displayed in the Timezone from where request \n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
