# Generated by Django 3.2.15 on 2022-09-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_auto_20220902_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
