# Generated by Django 3.2.15 on 2022-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0003_rename_ip_address_location_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='connection',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='continent_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='continent_name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='currency',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region_name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='security',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='time_zone',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
